- name: Fetch a file from remote host to control machine
  hosts: servers
  tasks:
    - name: Fetch file.txt from remote host
      ansible.builtin.fetch:
        src: /home/ubuntu/      
        dest: /install/framework/build
        flat: yes
