- name: Fetch a file from remote host to control machine
  hosts: servers
  tasks:
    - name: Fetch file.txt from remote host
      ansible.builtin.fetch:
        src:  /install/framework/build     
        dest: /home/ubuntu/
        flat: yes
