- name: Fetch a file from remote host to control machine
  hosts: servers
  tasks:
    - name: Fetch file.txt from remote host
      ansible.builtin.fetch:
        src: /home/ubuntu/inferyx-platform-test-v6.1.3.tar.gz       
        dest: /install/framework/build
        flat: yes
