---
- name: copy file between directories on remote with owner, group and file permissions (octal)
  hosts: servers
  tasks:
    - name: copy file to remote
      copy:
        src: /home/ubuntu/test_file   # Absolute path to the file on the local machine
        dest: $HOME/test_file2
        remote_src: true
        owner: "ubuntu"
        group: "ubuntu"
        mode: '0644'
