---
- name: Deploy docker-compose file
  hosts: servers
  become: yes
  tasks:    
    - name: Copy docker-compose.yml to remote host
      copy:
        src: /home/ubuntu/
        dest: /tmp/test_file
        mode: '0644'
