---
- name: copy file within remote
  hosts: servers
  tasks:
    - name: copy file to another directory on remote
      copy:
        src: /home/ubuntu/test_file   # Path to the file on the remote machine
        dest: /home/ubuntu/test_file
        remote_src: false
        owner: "ubuntu"
        group: "ubuntu"
        mode: '0644'
