---
- name: Deploy docker-compose file
  hosts: servers
  become: yes
  tasks:
    - name: Ensure the correct permissions on the local file
      command: sudo chmod 644 /home/ubuntu/test_file
      run_once: true

    - name: Ensure the correct permissions on the directory
      command: sudo chmod 755 /home/ubuntu
      run_once: true

    - name: Copy docker-compose.yml to remote host
      copy:
        src: /home/ubuntu/test_file
        dest: /tmp/test_file
        mode: '0644'
