- hosts: servers
  tasks:
    - name: Transfer file from ServerA to ServerB
      synchronize:
        src: /home/ubuntu/inferyx-platform-final-v6.1.3.tar.gz
        dest: /home/ubuntu/inferyx-platform-final-v6.1.3.tar.gz
