---
- name: run the task on host
  hosts: servers
  tasks:
    - name: copy file to remote
      copy:
        src: /home/ubuntu/test_file   # Replace with the actual path
        dest: $HOME/test_file
