- name: copy file between directories on remote with owner, group and file permissions (octal)
  copy:
    src: /home/ubuntu/test_file
    remote_src: true
    dest: $HOME/test_file2
    owner: "{{ ubuntu }}"
    group: "{{ ubuntu }}"
    mode: 0644
