---
- name: copy file from local to remote
  hosts: servers
  tasks:
    - name: copy file to remote
      copy:
        src: /home/ubuntu/   # Path to the file on the local machine
        dest: /home/remote_user/test_file2
        owner: "ubuntu"
        group: "ubuntu"
        mode: '0644'
