  
- name: Copy and extract foo.tgz into /var/lib/foo
  hosts: server1
  ansible.builtin.unarchive:
    src: inferyx-platform-final-v6.1.3.tar.gz
    dest: /install/framework/build

- name: Extract a file that is already on the remote machine (/tmp/foo.zip)
  ansible.builtin.unarchive:
    src: /home/ubuntu/inferyx-platform-final-v6.1.3.tar.gz
    dest: /install/framework/build
    remote_src: yes


