---
- hosts: servers
  become: yes

  vars:
    camunda_install_dir: /opt/camunda

  tasks:
    - name: Create Camunda directory
      file:
        path: "{{ camunda_install_dir }}"
        state: directory
        owner: camunda
        group: camunda
        mode: '0755'
      tags:
        - setup

    - name: Install prerequisites
      apt:
        name:
          - openjdk-8-jdk
          - unzip
        state: present
      tags:
        - prerequisites

    - name: Add Camunda user
      user:
        name: camunda
        shell: /bin/bash
        createhome: yes
      tags:
        - users

    - name: Download Camunda distribution
      get_url:
        url: https://camunda.org/release/camunda-bpm/tomcat/7.15/camunda-bpm-tomcat-7.15.0.tar.gz
        dest: /tmp/camunda.tar.gz
      tags:
        - download

    - name: Extract Camunda distribution
      ansible.builtin.unarchive:
        src: /tmp/camunda.tar.gz
        dest: "{{ camunda_install_dir }}"
        remote_src: yes
      tags:
        - extract

    - name: Set ownership and permissions
      file:
        path: "{{ camunda_install_dir }}/camunda-bpm-tomcat-7.15.0"
        owner: camunda
        group: camunda
        recurse: yes
      tags:
        - permissions

    - name: Ensure start-camunda.sh script is executable
      file:
        path: "{{ camunda_install_dir }}/camunda-bpm-tomcat-7.15.0/bin/start-camunda.sh"
        mode: '0755'
      tags:
        - permissions

    - name: Ensure shutdown-camunda.sh script is executable
      file:
        path: "{{ camunda_install_dir }}/camunda-bpm-tomcat-7.15.0/bin/shutdown-camunda.sh"
        mode: '0755'
      tags:
        - permissions

    - name: Set up Camunda as a service
      copy:
        dest: /etc/systemd/system/camunda.service
        content: |
          [Unit]
          Description=Camunda BPM Platform
          After=network.target

          [Service]
          User=camunda
          WorkingDirectory={{ camunda_install_dir }}/camunda-bpm-tomcat-7.15.0
          ExecStart={{ camunda_install_dir }}/camunda-bpm-tomcat-7.15.0/bin/start-camunda.sh
          ExecStop={{ camunda_install_dir }}/camunda-bpm-tomcat-7.15.0/bin/shutdown-camunda.sh
          Restart=always

          [Install]
          WantedBy=multi-user.target
      tags:
        - service

    - name: Reload systemd
      systemd:
        daemon_reload: yes
      tags:
        - service

    - name: Start Camunda service
      systemd:
        name: camunda
        state: started
      tags:
        - service

    - name: Enable Camunda service to start on boot
      systemd:
        name: camunda
        enabled: yes
      tags:
        - service
