---
- name: Extract tar file on remote host
  hosts: servers
  become: yes  # use this if you need sudo privileges
  tasks:
    - name: Ensure the file exists
      ansible.builtin.command:
        cmd: ls -l /home/ubuntu/inferyx-platform-final-v6.1.3
      register: result
      ignore_errors: yes

    - name: Debug file existence
      ansible.builtin.debug:
        msg: "{{ result.stdout_lines }}"

    - name: Extract tar file
      ansible.builtin.unarchive:
        src: /home/ubuntu/inferyx-platform-final-v6.1.3  # path to the tar file on the remote host
        dest: /install/framework/build/  # destination path on the remote host
        remote_src: yes  # indicates that the src is on the remote host
      when: result.rc == 0
