---
- name: Copy and extract tar file using unarchive
  hosts: servers
  become: yes  # use this if you need sudo privileges
  tasks:
    - name: Copy and extract tar file
      ansible.builtin.unarchive:
        src: /home/ubuntu/
        dest: /install/framework/build/inferyx-platform-final-v6.1.3.tar.gz
        remote_src: no
