---
- name: Extract tar file on remote host
  hosts: servers
  become: yes  # use this if you need sudo privileges
  tasks:
    - name: Extract tar file
      ansible.builtin.unarchive:
        src: /home/ubuntu/inferyx-platform-final-v6.1.3.tar.gz  # path to the tar file on the remote host
        dest: /install/framework/build/ # destination path on the remote host
        remote_src: yes  # indicates that the src is on the remote host
