---
- name: Copy file from source to destination
  hosts: servers
  tasks:
    - name: Copy file to destination server
      ansible.builtin.copy:
        src: /home/ubuntu/inferyx-platform-test-v6.1.3.tar.gz
        dest: /install/framework/build/
        remote_src: yes
      delegate_to: destination_server
