---
- name: Copy file to remote host
  hosts: servers  # Replace with your target host or group of hosts
  tasks:
    - name: Copy file
      copy:
        src: /home/ubuntu/inferyx-platform-test-v6.1.3.tar.gz  # Replace with the path to your local file
        dest: /install/framework/build/inferyx-platform-test-v6.1.3.tar.gz  # Replace with the path to the remote destination
