---
- name: Copy and extract inferyx platform tar file
  hosts: servers  # Replace with your actual host group or server name
  become: yes
  tasks:
    - name: Create user inferyx
      user:
        name: inferyx
        state: present
        create_home: yes
        shell: /bin/bash

    - name: Create necessary directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: inferyx
        group: inferyx
      loop:
        - /app/
        - /backup/
        - /install/
        - /install/framework/
        - /install/framework/build/

    - name: Verify directories
      command: ls -ld /app/ /backup/ /install/ /install/framework/ /install/framework/build/
      register: dir_listing

    - name: Print directory listings
      debug:
        msg: "{{ dir_listing.stdout_lines }}"

    - name: Copy inferyx-platform-test-v6.1.3.tar.gz to /install/framework/build/ directory on remote server
      ansible.builtin.copy:
        src: /tmp/ # Full path to your tar file on Ansible Controller
        dest: /install/framework/build/
        owner: inferyx
        group: inferyx
        mode: '0644'

    - name: Untar the file
      ansible.builtin.command: tar xvf /install/framework/build/inferyx-platform-test-v6.1.3.tar.gz -C /install/framework/build/
      become_user: inferyx

    - name: Navigate to the bin folder
      ansible.builtin.command: cd /install/framework/build/inferyx-platform-final-v6.0.0/deploy/bin
      become_user: inferyx

    - name: Run deploy_framework.sh script with required parameters
      ansible.builtin.command: ./deploy_framework.sh -a all -d framework -H localhost -P 27017 -u inferyx -p 20Inferyx19 -o all
      become_user: inferyx
