---
- name: Copy and extract inferyx platform tar file
  hosts: servers
  become: yes
  tasks:
    - name: Create user inferyx
      user:
        name: inferyx
        state: present
        create_home: yes
        shell: /bin/bash

    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: inferyx
        group: inferyx
      loop:
        - /app/
        - /backup/
        - /install/
        - /install/framework/
        - /install/framework/build/

    - name: Verify directories
      command: ls -ld /app/ /backup/ /install/ /install/framework/ /install/framework/build/
      register: dir_listing

    - name: Print directory listings
      debug:
        msg: "{{ dir_listing.stdout_lines }}"

    - name: Copy inferyx-platform-test-v6.1.3.tar.gz to /tmp/ directory on remote server
      copy:
        src: /home/ubuntu/inferyx-platform-test-v6.1.3.tar.gz  # Replace with the correct path on your Ansible Controller
        dest: /tmp/inferyx-platform-test-v6.1.3.tar.gz
        owner: inferyx
        group: inferyx
        mode: '0644'
        remote_src: yes  # Ensure to use remote_src option

    - name: Extract inferyx platform tar file
      ansible.builtin.command: tar xzf /tmp/inferyx-platform-test-v6.1.3.tar.gz -C /install/
      become_user: inferyx

    - name: Verify extracted files
      command: ls -l /install/inferyx-platform-test-v6.1.3/
      register: extracted_files_listing

    - name: Print extracted files listing
      debug:
        msg: "{{ extracted_files_listing.stdout_lines }}"
