---
- name: Copy and extract inferyx platform tar file
  hosts: servers
  become: yes

  tasks:
    - name: Create user inferyx
      user:
        name: inferyx
        state: present
        create_home: yes
        shell: /bin/bash

    - name: Create necessary directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /app/
        - /backup/
        - /install/
        - /install/framework/
        - /install/framework/build/

    - name: Verify directories
      command: ls -ld /app/ /backup/ /install/ /install/framework/ /install/framework/build/
      register: dir_listing

    - name: Print directory listings
      debug:
        msg: "{{ dir_listing.stdout_lines }}"

    - name: Copy inferyx-platform-test-v6.1.3.tar.gz to /install/framework/build/ directory on remote server using scp
      local_action: 
        module: command 
        cmd: scp -i /home/ubuntu/start.pem /home/ubuntu/inferyx-platform-test-v6.1.3.tar.gz ubuntu@{{ inventory_hostname }}:/install/framework/build/

    - name: Set ownership of the directories to inferyx user
      file:
        path: "{{ item }}"
        state: directory
        owner: inferyx
        group: inferyx
      loop:
        - /app/
        - /backup/
        - /install/
        - /install/framework/
        - /install/framework/build/

    - name: Set ownership of the copied tar file to inferyx user
      file:
        path: /install/framework/build/inferyx-platform-test-v6.1.3.tar.gz
        state: file
        owner: inferyx
        group: inferyx
        mode: '0644'

    - name: Extract inferyx platform tar file
      ansible.builtin.command: tar xzf /install/framework/build/inferyx-platform-test-v6.1.3.tar.gz -C /install/framework/build/
      become_user: inferyx

    - name: Verify extracted files
      command: ls -l /install/framework/build/
      register: extracted_files_listing

    - name: Print extracted files listing
      debug:
        msg: "{{ extracted_files_listing.stdout_lines }}"
