---
- name: Setup and Install Inferyx Project
  hosts: all
  become: yes
  vars:
    git_token: "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"
    project_directory: "/home/inferyx/git/inferyx"
    directories:
      - name: /backup
        mode: "0777"
      - name: /install
        mode: "0777"
      - name: /data
        mode: "0744"
      - name: /app
        mode: "0744"

  tasks:
    - name: Create project directory if it doesn't exist
      ansible.builtin.file:
        path: "{{ project_directory }}"
        state: directory
        owner: inferyx
        group: inferyx
        mode: "0755"

    - name: Change ownership of directories to inferyx user
      ansible.builtin.file:
        path: "{{ item.name }}"
        state: directory
        owner: inferyx
        group: inferyx
      with_items: "{{ directories }}"

    - name: Navigate to the project directory and clone the repository
      ansible.builtin.command: >
        cd "{{ project_directory }}" &&
        git clone https://github.com/inferyx/platform.git
      environment:
        GIT_TOKEN: "{{ git_token }}"
      become_user: inferyx
