---
- name: Create user inferyx and required directories
  hosts: servers
  become: yes
  tasks:

    - name: Create user inferyx
      user:
        name: inferyx
        state: present
        create_home: yes
        shell: /bin/bash

    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: inferyx
        group: inferyx
      with_items:
        - /app/
        - /backup/
        - /install/
        - /install/framework/
        - /install/framework/build/

    - name: Verify directories
      command: ls -ld /app/ /backup/ /install/ /install/framework/ /install/framework/build/
      register: dir_listing

    - name: Print directory listings
      debug:
        msg: "{{ dir_listing.stdout_lines }}"
