---
- name: Copy inferyx-platform-final-v6.1.3.tar.gz to another remote server using rsync
  hosts: serverA
  tasks:
    - name: Copy inferyx-platform-final-v6.1.3.tar.gz to serverB using rsync
      synchronize:
        mode: pull
        src: /home/ubuntu/inferyx-platform-final-v6.1.3.tar.gz
        dest: /install/framework/build/inferyx-platform-final-v6.1.3.tar.gz
        archive: yes
      delegate_to: "{{ servers }}"
      tags: release
