---
- name: Fetch the tar file from serverA and copy it to serverB
  hosts: serverA
  tasks:
    - name: Fetch the tar file from serverA
      fetch:
        src: /home/ubuntu/inferyx-platform-test-v6.1.3.tar.gz
        dest: /tmp/inferyx-platform-test-v6.1.3.tar.gz
      delegate_to: serverA

- hosts: serverB
  tasks:
    - name: Copy the tar file to serverB
      copy:
        src: /tmp/inferyx-platform-test-v6.1.3.tar.gz
        dest: /install/framework/build/inferyx-platform-test-v6.1.3.tar.gz













- hosts: servers
  tasks:
    - name: Copy the tar file to serverB
      copy:
        src: /home/ubuntu/
        dest: 
