- hosts: servers
  tasks:
    - name: Copy the tar file to serverB
      copy:
        src: /home/ubuntu/inferyx-platform-test-v6.1.3.tar.gz
        dest: /install/framework/build/inferyx-platform-test-v6.1.3.tar.gz
