---
- name: Copy inferyx-platform-final-v6.1.3.tar.gz to another remote server using rsync
  hosts: server1
  tasks:
    - name: Copy inferyx-platform-final-v6.1.3.tar.gz to server2 using rsync
      synchronize:
        mode: push
        src: /home/ubuntu/inferyx-platform-final-v6.1.3.tar.gz
        dest: /install/framework/build/inferyx-platform-final-v6.1.3.tar.gz
        archive: yes
      delegate_to: server2
      tags: release
