- name: Install Java 8 and Java 11
  hosts: servers
  become: yes
  tasks:
    - name: Install Java 8
      apt:
        name: openjdk-8-jdk
        state: present

    - name: Install Java 11
      apt:
        name: openjdk-11-jdk
        state: present
