---
- name: Copy inferyx-platform-test-v6.1.3.tar.gz from instance A to instance B
  hosts: instance_a
  tasks:
    - name: Copy inferyx-platform-test-v6.1.3.tar.gz to instance B
      ansible.builtin.shell: >
        scp -o StrictHostKeyChecking=no /tmp/inferyx-platform-test-v6.1.3.tar.gz ec2-user@{{ hostvars['instance_b'].ansible_host }}:/tmp/inferyx-platform-test-v6.1.3.tar.gz
      become: yes
      become_user: inferyx

- name: Set permissions on instance B
  hosts: instance_b
  tasks:
    - name: Ensure the correct permissions
      ansible.builtin.command: chown inferyx:inferyx /tmp/inferyx-platform-test-v6.1.3.tar.gz
      become: yes
